try:
   # x = 23 
    print(x)
except:
    print("An exception occurred, Please Try again")
    x = 23
    print(x
    
    